export const htmlId: string = 'html'
export const headId: string = 'head'
export const bodyId: string = 'body'
export const contentId: string = 'content'
export const unplacedElementsId: string = 'unplacedElements'
