export const htmlId: string = 'html'
export const headId: string = 'head'
export const bodyId: string = 'body'
export const contentId: string = 'content'
export const terminalId: string = 'terminal'
export const logId: string = 'log'
export const commandLineId: string = 'commandLine'
export const unplacedElementsId: string = 'unplacedElements'
