name: Continuous integration
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '21'
    - name: Install and test
      run: | 
        npm install
        npm test
